fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "2.6.0"
    #snmp: "git://github.com/razorsedge/puppet-snmp.git"
  symlinks:
    hp_mcp: "#{source_dir}"
